(function () {
const { store } = window.VetraStore;
const { icon } = window.VetraIcons;
const { render: renderView, form } = window.VetraViews;

const app = document.querySelector('#app');
const overlay = document.querySelector('#overlay-root');
const toastRoot = document.querySelector('#toast-root');
const routes = [['overview','Visão geral','grid','Visão'],['records','Registros','records','Operação'],['flows','Fluxos','flow','Operação'],['calendar','Agenda','calendar','Planejamento'],['organizations','Organizações','directory','Base'],['tasks','Pendências','tasks','Base'],['reports','Relatórios','chart','Leitura'],['activity','Atividade','activity','Sistema'],['settings','Configurações','settings','Sistema']];
const titles = Object.fromEntries(routes.map(([id,label]) => [id,label]));
const collections = { records:'records', flows:'flows', organizations:'organizations', calendar:'events', tasks:'tasks' };
const labels = { records:'Registro', flows:'Fluxo', organizations:'Organização', calendar:'Evento', tasks:'Pendência' };

const baseRoute = route => route.startsWith('detail:') ? route.split(':')[1] : route;
function toast(message, tone = '') { const item = document.createElement('div'); item.className = `toast ${tone}`; item.textContent = message; toastRoot.append(item); window.setTimeout(() => item.remove(), 2800); }
function closeOverlay() { overlay.replaceChildren(); }
function open(content) { overlay.innerHTML = content; }
function nav() { let previous = ''; return routes.map(([route,label,glyph,section]) => { const group = section !== previous ? `<div class="side-section">${section}</div>` : ''; previous = section; return `${group}<button class="nav-button" data-route="${route}"><span class="nav-icon">${icon(glyph)}</span><span class="nav-label">${label}</span></button>`; }).join(''); }
function shell(state) { const current = baseRoute(state.route); const crumb = titles[current] || 'Gestão'; return `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark">${icon('mark')}</span><div class="brand-name">GESTÃO<small>SYSTEM</small></div></div><nav class="nav" aria-label="Navegação principal">${nav()}</nav><div class="sidebar-bottom"><button class="new-button" data-add="records">${icon('plus')}Novo registro</button><div class="local-mark"><i></i><span>LOCAL</span></div></div></aside><section class="workspace"><header class="topbar"><div class="top-actions"><button class="icon-control mobile-menu" data-menu aria-label="Abrir menu">${icon('grid')}</button><span class="crumb">Gestão&nbsp;&nbsp;/&nbsp;&nbsp;<b>${crumb}</b></span></div><div class="top-actions"><button class="icon-control" data-route="activity" aria-label="Atividade">${icon('bell')}</button><div class="identity"><div class="identity-avatar">JV</div><span>Workspace</span></div></div></header><main class="main" id="main-content">${renderView(state.route,state)}</main></section></div>`; }
function add(type, data) { const collection = collections[type] || 'records'; const entity = { id:store.uid(type), createdAt:new Date().toISOString(), ...data }; store.update(state => { state[collection].unshift(entity); state.activity.unshift({id:store.uid('activity'),kind:labels[type] || 'Registro',label:entity.title,at:entity.createdAt}); state.route=type; }); closeOverlay(); toast(`${labels[type] || 'Registro'} criado.`); }
function remove(route,id) { const collection = collections[route]; if (!collection) return; store.update(state => { const item=state[collection].find(entry => entry.id===id); state[collection]=state[collection].filter(entry => entry.id!==id); state.activity.unshift({id:store.uid('activity'),kind:'Exclusão',label:item?.title || labels[route],at:new Date().toISOString()}); state.route=route; }); closeOverlay(); toast('Item removido.'); }
function confirm(title, action) { open(`<div class="modal-backdrop" data-modal-close><section class="modal"><header class="modal-head"><div><h2>${title}</h2><p>Sistema de Gestão</p></div><button class="close" data-modal-close aria-label="Fechar">×</button></header><footer class="modal-foot"><button class="button" data-modal-close>Cancelar</button><button class="button danger" data-confirm>Confirmar</button></footer></section></div>`); overlay.querySelector('[data-confirm]').addEventListener('click', action); }
function bind() { document.querySelectorAll('[data-route]').forEach(button => button.addEventListener('click',() => store.update(state => { state.route=button.dataset.route; }))); document.querySelectorAll('[data-add]').forEach(button => button.addEventListener('click',() => open(form(button.dataset.add)))); const menu=document.querySelector('[data-menu]'); if(menu) menu.addEventListener('click',() => document.querySelector('#sidebar').classList.toggle('open')); const search=document.querySelector('#collectionSearch'); if(search) search.addEventListener('input',() => document.querySelectorAll('[data-search]').forEach(row => { row.hidden=!row.dataset.search.includes(search.value.trim().toLowerCase()); })); document.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click',() => { const [route,id]=button.dataset.delete.split(':'); confirm('Excluir item',() => remove(route,id)); })); const reset=document.querySelector('[data-reset]'); if(reset) reset.addEventListener('click',() => confirm('Limpar dados locais',() => { store.reset(); closeOverlay(); toast('Dados locais removidos.'); })); }
overlay.addEventListener('click',event => { if(event.target.matches('[data-modal-close]')) closeOverlay(); });
overlay.addEventListener('submit',event => { const formNode=event.target.closest('form[data-create]'); if(!formNode) return; event.preventDefault(); add(formNode.dataset.create,Object.fromEntries(new FormData(formNode))); });
document.addEventListener('keydown',event => { if(event.key==='Escape') closeOverlay(); });
function paint(state) { app.className=''; app.innerHTML=shell(state); document.querySelectorAll('.nav-button').forEach(button => button.classList.toggle('active',button.dataset.route===baseRoute(state.route))); bind(); }
store.subscribe(paint); paint(store.get());
}());
